from __future__ import annotations

from enum import Enum


class TrackStatus(str, Enum):
    """Lifecycle status for one tracked object."""

    TENTATIVE = "tentative"
    CONFIRMED = "confirmed"
    LOST = "lost"


class AlertLevel(str, Enum):
    """Severity level for alerts in blind-spot monitoring."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Alert category generated by the pipeline."""

    BLIND_SPOT = "blind_spot"
    PREDICTED_COLLISION = "predicted_collision"
    TRACK_LOST = "track_lost"
